### ISSUE TITLE
一颗玉米的个人博客

### ISSUE THREAD

**Issue by kkk48ku** [kkk48ku/comment#1]
https://www.yiwangzhe.cn/detail?articleId=5201904121910481&messageNum=0&pageView=1 

 这是一个前端爱好者自己编写的技术博客，会不定期更新自己的技术收藏，欢迎关注，
    如果有相同爱好者可以加微信或者关注博主github，博客所用技术栈（前台：vue全家桶+axios+element-ui+mongodb；
    后台：vue+node+express+mongodb），博客更新技术范围：html，css，javascript，vue，node，express，mongodb等等；
    vue博客前后台，mongodb后台，博客统计使用百度统计、友盟统计和google全球统计，在此做出感谢。

**Comment by kkk48ku** [comment]
测试

**Comment by kkk48ku** [comment]
### ce

**Comment by laomao-murry** [comment]
这就没意思了啊，还转载别人的博客，自己写技术啊，我以为有长篇大论呢

**Comment by laomao-murry** [comment]
怎么调到github上了，哈哈
